I1=imread('D:\精通matlab数字图像处理与识别书中源码\chapter5\bacteria.BMP');
fcoef=fft2(double(I1));%做fft变换
spectrum=fftshift(fcoef);%将零点移到中心
temp=log(1+abs(spectrum));%对幅值做对数变换以压缩动态范围
subplot(1,2,1);
imshow(temp,[]);
title('FFT');
subplot(1,2,2);
imshow(I1);
title('source');
I2=imread('D:\精通matlab数字图像处理与识别书中源码\chapter5\babyNew.bmp');
fcoef=fft2(double(I2));%做fft变换
spectrum=fftshift(fcoef);%将零点移到中心
temp=log(1+abs(spectrum));
figure;
subplot(1,2,1);
imshow(temp,[]);
title('FFT');
subplot(1,2,2);
imshow(I2);
title('Source');
