I=imread('D:\精通matlab数字图像处理与识别书中源码\chapter5\baby_noise.bmp');
%生成滤镜
ff=imgaussflpf(I,20);
%应用滤镜
out=imfreqfilt(I,ff);
figure(1);
subplot(2,2,1);
imshow(I);
title('source');
%计算FFT并显示
temp=fft2(I);
temp=fftshift(temp);
temp=log(1+abs(temp));
figure(2);
subplot(2,2,1);
imshow(temp,[]);
title('source');
figure(1);
subplot(2,2,2);
imshow(out,[]);
title('gauss LPF,sigma=20');
temp=fft2(out);
temp=fftshift(temp);
temp=log(1+abs(temp));
figure(2);
subplot(2,2,2);
imshow(temp,[]);
title('gauss LPF,sigma=20');
ff=imgaussflpf(I,40);
out=imfreqfilt(I,ff);
figure(1);
subplot(2,2,3);
imshow(out,[]);
title('gauss LPF,sigma=40');
temp=fft2(out);
temp=fftshift(temp);
temp=log(1+abs(temp));
figure(2);
subplot(2,2,3);
imshow(temp,[]);
title('gauss LPF,sigma=40');
ff=imgaussflpf(I,60);
out=imfreqfilt(I,ff);
figure(1);
subplot(2,2,4);
imshow(out,[]);
title('guass LPF,sigma=60');
temp=fft2(out);
temp=fftshift(temp);
temp=log(1+abs(temp));
figure(2);
subplot(2,2,4);
imshow(temp,[]);
title('gauss LPF,sigma=60');