I=imread('D:\精通matlab数字图像处理与识别书中源码\chapter5\bacteria.BMP');
w1=fspecial('sobel');%得到水平sobel模板
w2=w1';%转置得到竖直soble模板
G1=imfilter(I,w1);%水平Sobel梯度
G2=imfilter(I,w2);%竖直Sobel梯度
G=abs(G1)+abs(G2);%Sobel梯度
figure,imshow(G1,[]);
figure,imshow(G2,[]);
figure,imshow(G,[]);
